[package]
name = "parcer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = "3.17.0"
colored = "3.0.0"
logos = "0.15.0"
